joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    base_frame_id: base_link
    enable_odom_tf: true

    left_wheel_names: ["chassis_to_left_wheel_joint"]
    right_wheel_names: ["chassis_to_right_wheel_joint"]
    wheel_separation: 0.12  # m
    wheel_radius: 0.03  # m

    publish_rate: 50.0  # Hz
    cmd_vel_timeout: 2.0  # s - how long to wait before stopping robot if no /cmd_vel msg received 
    

    linear:
      x:
        max_velocity: 0.5  # m/s
        min_velocity: -0.5  # m/s

        max_acceleration: 2.0  # m/s^2
        min_acceleration: -1.5  # m/s^2

    angular:
      z: 
        max_velocity: 2.0  # rad/s
        min_velocity: -2.0  # rad/s
